### ISSUE TITLE
problem with answers

### ISSUE THREAD

**Issue by alimp5** [kickboxio/kickbox-python#6]
Hi dear admin
when I run the script in a Linux system or windows system, just below line is reported and i can't see the state of reason field.

``` python
import kickbox
client   = kickbox.Client('344-----API-----9a6f86')
kickbox  = client.kickbox()
response = kickbox.verify("ali_parkour68@yahoo.com")
print response
```

i get below answer.
`<kickbox.http_client.response.Response object at 0x02AD0250>`

but i want to see the states of reason field.
but with CURL, i can see the reason field. plz check and fix this issue.
tnx dear :x:

**Comment by schaitanya** [comment]
Please try, `response.body['result']`

**Comment by alimp5** [comment]
Thanks a lot :X
